### ISSUE TITLE
wrap in failjure the postal exception on mail send

### ISSUE THREAD

**Issue by jaromil** [Commonfare-net/just-auth#27]
When `postal/send-message` is used In [messaging.clj](/Commonfare-net/just-auth/blob/master/src/just_auth/messaging.clj#L48#L48) and a failure occurs in postal, it will throw an exception that is not catched. Since just-auth uses failjure, this should be reported inside it so that the caller can handle it normally.

**Comment by aspasia** [comment]
I cannot reproduce this when I for example try to send and activation message with wrong configuration. Can you check that this is still the case please?

**Comment by jaromil** [comment]
as discussed offline, closing this as seems to be fixed
