### ISSUE TITLE
Arity error

### ISSUE THREAD

**Issue by borkdude** [Commonfare-net/just-auth#29]
[clj-kondo](https://github.com/borkdude/clj-kondo) detected the following arity error:

```
src/just_auth/core.clj:179:17: error: Wrong number of args (3) passed to auxiliary.translation/locale
```

https://github.com/Commonfare-net/just-auth/blob/a7a669219715ce87e751b3bb506b81eaa80f2646/src/just_auth/core.clj#L179

**Comment by aspasia** [comment]
fixed with https://github.com/Commonfare-net/just-auth/commit/7c73cef26cabc1f2648e4bc2a963050e2ca24a84
